# Generated by Django 4.0.3 on 2022-04-02 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_children', models.CharField(max_length=100)),
                ('family_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_of_children', to='Family.parents')),
            ],
        ),
    ]
